
export const {
    NEXT_PUBLIC_SECRET_MNEMONIC,
    NEXT_PUBLIC_SECRET_CHAIN_ENDPOINT,
    NEXT_PUBLIC_SECRET_CHAIN_ID,
    NEXT_PUBLIC_SECRET_TOKEN,
    NEXT_PUBLIC_CONSUMER_MNEMONIC,
    NEXT_PUBLIC_CONSUMER_CHAIN_ENDPOINT,
    NEXT_PUBLIC_CONSUMER_CHAIN_ID,
    NEXT_PUBLIC_CONSUMER_TOKEN,
    NEXT_PUBLIC_CONSUMER_PREFIX,
    NEXT_PUBLIC_CONSUMER_GAS_PRICE,
    NEXT_PUBLIC_CONSUMER_DECIMALS,
} = process.env